// * action types
// export const SEARCH_ADDRESS_SUCCESS = 'SEARCH_ADDRESS_SUCCESS';
// export const SEARCH_ADDRESS_FAILURE = 'SEARCH_ADDRESS_FAILURE';
export const SEARCH_ADDRESS = 'SEARCH_ADDRESS';

// export const AUTHENTICATE = 'AUTHENTICATE';
