//action types

export const SEARCH_ADDRESS_PENDING = 'SEARCH_ADDRESS_PENDING';
export const SEARCH_ADDRESS_SUCCESS = 'SEARCH_ADDRESS_SUCCESS';
export const SEARCH_ADDRESS_FAILURE = 'SEARCH_ADDRESS_FAILURE';
export const SEARCH_ADDRESS = 'SEARCH_ADDRESS';

export const AUTHENTICATE = 'AUTHENTICATE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
